spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ledgerbank_account}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
app:
  messaging:
    pix-requested-exchange: pix.requested
    pix-requested-routing-key: pix.transfer.requested
    outbox-publish-batch-size: 50
server:
  port: ${SERVER_PORT:8081}
